on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: copy sample songs
        run: |
          mkdir src/tracks
          mkdir src/tracks/welcome
          mkdir src/tracks/intro
          mkdir src/tracks/ending
          cp samples/ai.mp3 src/tracks/welcome/i-love-you.mp3
          cp samples/ai.mp3 src/tracks/welcome/never-gonna-give-you-up.mp3
          cp samples/ai.mp3 src/tracks/intro/wedding-progress.mp3
          cp samples/ai.mp3 src/tracks/intro/one-thousand-years.mp3
          cp samples/ai.mp3 src/tracks/intro/new-time-ok.mp3
          cp samples/ai.mp3 src/tracks/ending/hello.mp3
          cp samples/ai.mp3 src/tracks/ending/goodbye-kiss.mp3
      - run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
